import { Profile } from "./frame-interfaces/profile";
import {
  abstractFunctionKeywords,
  abstractKeyword,
  abstractProcedureKeywords,
  abstractPropertyKeywords,
  assertKeyword,
  callKeyword,
  classKeyword,
  commentMarker,
  constantKeyword,
  constructorKeyword,
  eachKeyword,
  elseKeyword,
  enumKeyword,
  forKeyword,
  functionKeyword,
  ifKeyword,
  interfaceKeyword,
  letKeyword,
  mainKeyword,
  printKeyword,
  privateFunctionKeywords,
  privateProcedureKeywords,
  privatePropertyKeywords,
  procedureKeyword,
  propertyKeyword,
  recordKeyword,
  repeatKeyword,
  returnKeyword,
  setKeyword,
  testKeyword,
  throwKeyword,
  tryKeyword,
  variableKeyword,
  whileKeyword,
} from "./keywords";

export class DefaultProfile implements Profile {
  name: string = "default_profile";
  globals: string[] = [
    mainKeyword,
    procedureKeyword,
    functionKeyword,
    classKeyword,
    abstractKeyword,
    interfaceKeyword,
    recordKeyword,
    constantKeyword,
    enumKeyword,
    testKeyword,
    commentMarker,
  ];
  statements: string[] = [
    assertKeyword,
    callKeyword,
    eachKeyword,
    elseKeyword,
    forKeyword,
    ifKeyword,
    letKeyword,
    printKeyword,
    repeatKeyword,
    returnKeyword,
    setKeyword,
    throwKeyword,
    tryKeyword,
    variableKeyword,
    whileKeyword,
    commentMarker,
  ];
  class_members: string[] = [
    constructorKeyword,
    functionKeyword,
    procedureKeyword,
    propertyKeyword,
    abstractFunctionKeywords,
    abstractProcedureKeywords,
    abstractPropertyKeywords,
    privateFunctionKeywords,
    privateProcedureKeywords,
    privatePropertyKeywords,
    commentMarker,
  ];
  require_log_on: boolean = false;
  can_load_only_own_files: boolean = false;
  show_user_and_profile: boolean = false;
}
